server:
  port: 8080
  servlet:
    context-path: /NextFilm
rest:
  auth-open: true #\u5982\u679C\u4E3Atrue \u5219\u5F00\u542FJWT\u7684\u9A8C\u8BC1

jwt:
  header: Authorization #http\u8BF7\u6C42\u5934\u6240\u9700\u8981\u7684\u5B57\u6BB5
  secret: mySecret      #jwt\u79D8\u94A5
  expiration: 604800    #7\u5929 \u5355\u4F4D\uFF1A\u79D2
#  auth-path: auth       #\u8BA4\u8BC1\u8BF7\u6C42\u7684\u8DEF\u5F84
  md5-key: randomKey    #md5\u52A0\u5BC6\u6DF7\u6DC6key

mybatis-plus:
  mapper-locations: classpath*:com/next/demo/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:\u6570\u636E\u5E93ID\u81EA\u589E   1:\u7528\u6237\u8F93\u5165id 2:\u5168\u5C40\u552F\u4E00id\uFF08IdWorker\uFF09 3:\u5168\u5C40\u552F\u4E00ID\uFF08uuid\uFF09
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/next_film?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat

logging:
  level.root: info
  level.com.next.demo: debug
  path: logs/
  file: next-film.log

film:
  img-pre: http//ima.nextfilm.cn/

order:
  file-path-pre: D:/ChromeCoreDownloads/
  qrcode-path-pre: D:/ChromeCoreDownloads/nextfilm/

